// Generated by CoffeeScript 1.12.2
(function() {
  var BFS, tree;

  tree = [[1, [3, [4], [[5, 8], 7], 2], 1, [9]], [1, [3, [4], [[5, 8], 7], 2], 1, [[1, [3, [4], [[5, 8], 7], 2], 1, [11]]]]];

  BFS = function(tree) {
    var recur;
    recur = function(tree, max, ccs) {
      var ___ccs, ___max, ref;
      ref = tree.reduce((function(arg, leaf) {
        var _ccs, _max;
        _max = arg[0], _ccs = arg[1];
        if (!Array.isArray(leaf)) {
          if (_max > leaf) {
            return [_max, _ccs];
          } else {
            return [leaf, _ccs];
          }
        } else {
          return [
            _max, _ccs.concat(function(__max, __ccs) {
              return recur(leaf, __max, __ccs);
            })
          ];
        }
      }), [max, ccs]), ___max = ref[0], ___ccs = ref[1];
      if (___ccs.length === 0) {
        return ___max;
      } else {
        return ___ccs[0](___max, ___ccs.slice(1));
      }
    };
    return recur(tree, 0, []);
  };

  console.log(BFS(tree));

}).call(this);
