// Generated by CoffeeScript 1.12.2
(function() {
  var DFS, tree;

  tree = [[1, [3, [4], [[5, 8], 7], 2], 1, [9]], [1, [3, [4], [[5, 8], 7], 2], 1, [[1, [3, [4], [[5, 8], 7], 2], 1, [11]]]]];

  DFS = function(tree) {
    var recur;
    recur = function(tree, max) {
      var _max, head, tail;
      head = tree[0];
      tail = tree.slice(1);
      if (!Array.isArray(head)) {
        _max = (max < head ? head : max);
        if (tail.length === 0) {
          return _max;
        } else {
          return recur(tail, _max);
        }
      } else {
        return recur(tail, recur(head, max));
      }
    };
    return recur(tree, 0);
  };

  console.log(DFS(tree));

}).call(this);
