// Generated by CoffeeScript 1.10.0
(function() {
  var intensity, main;

  main = function() {
    var listener, soundSources;
    soundSources = [[0, 0], [10, 0], [0, 10], [10, 10]];
    return listener = [5, 5];
  };

  intensity = function(power, radius) {
    return power / (4 * Math.PI * radius);
  };

}).call(this);
