// Generated by CoffeeScript 1.12.2
(function() {
  var a, b, c, d, oprs, ref, results;

  console.clear();

  oprs = ["+", "-", "*", "/"];

  ref = [4, 0, 5, 9], a = ref[0], b = ref[1], c = ref[2], d = ref[3];

  results = [];

  (function() {
    var expr, f1, f2, f3, f4, i, len, o1, o2, o3, ref1, result, results1, val;
    ref1 = ["+", "-"];
    results1 = [];
    for (i = 0, len = ref1.length; i < len; i++) {
      f1 = ref1[i];
      results1.push((function() {
        var j, len1, ref2, results2;
        ref2 = ["+", "-"];
        results2 = [];
        for (j = 0, len1 = ref2.length; j < len1; j++) {
          f2 = ref2[j];
          results2.push((function() {
            var k, len2, ref3, results3;
            ref3 = ["+", "-"];
            results3 = [];
            for (k = 0, len2 = ref3.length; k < len2; k++) {
              f3 = ref3[k];
              results3.push((function() {
                var l, len3, ref4, results4;
                ref4 = ["+", "-"];
                results4 = [];
                for (l = 0, len3 = ref4.length; l < len3; l++) {
                  f4 = ref4[l];
                  results4.push((function() {
                    var len4, m, results5;
                    results5 = [];
                    for (m = 0, len4 = oprs.length; m < len4; m++) {
                      o1 = oprs[m];
                      results5.push((function() {
                        var len5, n, results6;
                        results6 = [];
                        for (n = 0, len5 = oprs.length; n < len5; n++) {
                          o2 = oprs[n];
                          results6.push((function() {
                            var len6, o, results7;
                            results7 = [];
                            for (o = 0, len6 = oprs.length; o < len6; o++) {
                              o3 = oprs[o];
                              expr = "(" + f1 + a + ")" + o1 + "(" + f2 + b + ")" + o2 + "(" + f3 + c + ")" + o3 + "(" + f4 + d + ")";
                              val = eval(expr);
                              result = expr + "=" + val;
                              console.log(result);
                              if (val === 10) {
                                results7.push(results.push(result));
                              } else {
                                results7.push(void 0);
                              }
                            }
                            return results7;
                          })());
                        }
                        return results6;
                      })());
                    }
                    return results5;
                  })());
                }
                return results4;
              })());
            }
            return results3;
          })());
        }
        return results2;
      })());
    }
    return results1;
  })();

  if (results.length === 0) {
    alert("nothing");
  } else {
    alert(results.join("\n"));
  }

}).call(this);
